# generated by datamodel-codegen:
#   filename:  api-docs.json
#   timestamp: 2026-01-14T16:05:06+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel


class UserRequestDto(BaseModel):
    username: str
    email: str
    password: str
    role: str


class UserResponseDto(BaseModel):
    id: int | None = None
    username: str | None = None
    email: str | None = None
    role: str | None = None


class Status(Enum):
    CREATED = 'CREATED'
    INPROGRESS = 'INPROGRESS'
    DONE = 'DONE'


class Ingredient(BaseModel):
    id: int | None = None
    name: str | None = None
    quantity: int | None = None


class Role(Enum):
    CUSTOMER = 'CUSTOMER'
    SELLER = 'SELLER'
    ADMIN = 'ADMIN'


class User(BaseModel):
    id: int | None = None
    username: str | None = None
    email: str | None = None
    password: str | None = None
    role: Role | None = None
    createdAt: datetime | None = None


class UpdateOrderStatusRequest(BaseModel):
    status: str | None = None


class IngredientDto(BaseModel):
    id: int | None = None
    name: str | None = None
    quantity: int | None = None


class UserDto(BaseModel):
    id: int | None = None
    username: str | None = None


class IngredientRequestDto(BaseModel):
    name: str
    quantity: int


class IngredientResponseDto(BaseModel):
    id: int | None = None
    name: str | None = None
    quantity: int | None = None


class CreateOrderDto(BaseModel):
    ingredientIds: list[int] | None = None
    comment: str | None = None


class MessageRequestDto(BaseModel):
    senderId: int
    receiverId: int
    content: str


class MessageResponseDto(BaseModel):
    id: int | None = None
    content: str | None = None
    sentAt: datetime | None = None
    sender: UserDto | None = None
    receiver: UserDto | None = None


class OrderDto(BaseModel):
    id: int | None = None
    userId: int | None = None
    ingredientIds: list[int] | None = None
    createdAt: str | None = None
    status: str | None = None


class RegisterRequest(BaseModel):
    username: str | None = None
    email: str | None = None
    password: str | None = None


class AuthRequest(BaseModel):
    username: str | None = None
    password: str | None = None


class AuthFullResponse(BaseModel):
    token: str | None = None
    user: UserResponseDto | None = None


class PagedResponseUserResponseDto(BaseModel):
    content: list[UserResponseDto] | None = None
    page: int | None = None
    size: int | None = None
    totalElements: int | None = None
    totalPages: int | None = None
    first: bool | None = None
    last: bool | None = None
    hasNext: bool | None = None
    hasPrevious: bool | None = None


class SortObject(BaseModel):
    direction: str | None = None
    nullHandling: str | None = None
    ascending: bool | None = None
    property: str | None = None
    ignoreCase: bool | None = None


class NotificationDto(BaseModel):
    id: int | None = None
    message: str | None = None
    type: str | None = None
    orderId: int | None = None
    status: str | None = None
    createdAt: datetime | None = None


class OrderCreatedEvent(BaseModel):
    orderId: int | None = None
    userId: int | None = None
    ingredientIds: list[int] | None = None
    status: str | None = None
    createdAt: datetime | None = None


class CoffeeOrder(BaseModel):
    id: int | None = None
    user: User | None = None
    ingredients: list[Ingredient] | None = None
    createdAt: datetime | None = None
    status: Status | None = None
    comment: str | None = None


class CoffeeOrderResponse(BaseModel):
    id: int | None = None
    user: UserDto | None = None
    ingredients: list[IngredientDto] | None = None
    createdAt: datetime | None = None
    status: str | None = None
    comment: str | None = None


class PageableObject(BaseModel):
    pageNumber: int | None = None
    pageSize: int | None = None
    unpaged: bool | None = None
    paged: bool | None = None
    offset: int | None = None
    sort: list[SortObject] | None = None


class PageNotificationDto(BaseModel):
    totalPages: int | None = None
    totalElements: int | None = None
    pageable: PageableObject | None = None
    last: bool | None = None
    first: bool | None = None
    numberOfElements: int | None = None
    size: int | None = None
    content: list[NotificationDto] | None = None
    number: int | None = None
    sort: list[SortObject] | None = None
    empty: bool | None = None


class PageCoffeeOrderResponse(BaseModel):
    totalPages: int | None = None
    totalElements: int | None = None
    pageable: PageableObject | None = None
    last: bool | None = None
    first: bool | None = None
    numberOfElements: int | None = None
    size: int | None = None
    content: list[CoffeeOrderResponse] | None = None
    number: int | None = None
    sort: list[SortObject] | None = None
    empty: bool | None = None
