# generated by datamodel-codegen:
#   filename:  sdl.gql
#   timestamp: 2026-01-16T15:34:28+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Literal, Optional
from typing_extensions import TypeAlias #импорт из другой библиотеки

from pydantic import BaseModel, Field

Boolean: TypeAlias = bool
"""
The `Boolean` scalar type represents `true` or `false`.
"""


ID: TypeAlias = int
"""
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
"""


Int: TypeAlias = int
"""
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
"""


String: TypeAlias = str
"""
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
"""


class CoffeeOrderStatus(Enum):
    CREATED = 'CREATED'
    DONE = 'DONE'
    INPROGRESS = 'INPROGRESS'


class Role(Enum):
    ADMIN = 'ADMIN'
    CUSTOMER = 'CUSTOMER'
    SELLER = 'SELLER'


class Ingredient(BaseModel):
    id: ID
    name: String
    quantity: Int
    typename__: Literal['Ingredient'] | None = Field('Ingredient', alias='__typename')


class User(BaseModel):
    email: String
    id: ID
    role: String
    username: String
    typename__: Literal['User'] | None = Field('User', alias='__typename')


class CoffeeOrder(BaseModel):
    createdAt: String
    id: ID
    ingredients: list[Ingredient]
    status: String
    user: User
    typename__: Literal['CoffeeOrder'] | None = Field('CoffeeOrder', alias='__typename')


class Message(BaseModel):
    content: String
    id: ID
    receiver: User
    sender: User
    sentAt: String
    typename__: Literal['Message'] | None = Field('Message', alias='__typename')
